# -*- coding: utf-8 -*-
"""Riassunti dei giochi della collezione.

Scritti rielaborando quanto si trova su BoardGameGeek, La Tana dei Goblin e sui
siti degli editori: raccontano in due righe che cosa si fa concretamente durante
una partita. Sono il contenuto della colonna "Descrizione" di dati/giochi.xlsx.
"""

DESCRIZIONI = {
    "Pictureka": "Caccia al dettaglio su tabelloni affollati di oggetti disegnati alla rinfusa: le carte chiedono di trovarne uno e vince chi lo individua per primo. Alcune missioni si giocano a tempo, altre a colpo d'occhio.",
    "Forza 4": "Il classico a gravità: si lasciano cadere i gettoni nelle colonne cercando di allinearne quattro in orizzontale, verticale o diagonale prima dell'avversario.",
    "Non ti arrabbiare": "Il gioco della tradizione: si tirano i dadi per portare le proprie quattro pedine dal via al traguardo, rispedendo a casa chi si trova sulla casella d'arrivo.",
    "Dixit": "Il narratore descrive con una frase una delle sue illustrazioni oniriche; gli altri giocano una carta che possa ingannare e poi tutti votano. Si guadagna solo se qualcuno indovina, ma non se indovinano tutti.",
    "Scythe": "Europa alternativa degli anni Venti, fra contadini e mech a vapore: si alternano azioni su una plancia personale per produrre, espandersi e combattere, piazzando le proprie stelle prima degli altri.",
    "Last Friday": "Omaggio agli slasher anni Ottanta: un giocatore muove l'assassino in segreto su una mappa, gli altri sono i ragazzi che cercano di sopravvivere e di intuirne il percorso. Si gioca in quattro capitoli concatenati.",
    "Challengers! Beach Cup": "Un torneo a eliminazione: ogni round si aggiungono carte al proprio mazzo e lo si fa scontrare in automatico con quello dell'avversario di turno. Tutti giocano insieme e alla fine restano due in finale.",
    "Smash Up": "Si mescolano due fazioni assurde — pirati zombie, dinosauri robot — e si usa il mazzo risultante per conquistare basi prima degli altri, con effetti che si combinano in modi imprevisti.",
    "Las Vegas Party": "Si piazzano i propri dadi nei casinò e chi ha la maggioranza in uno ne incassa il premio. Il difficile è capire dove insistere e dove lasciar perdere, perché due pari merito si annullano.",
    "Twilight Imperium (quarta edizione)": "Il kolossal della fantascienza: ogni razza galattica costruisce flotte, colonizza pianeti, vota nel consiglio e tratta con le altre per arrivare per prima ai punti vittoria. Una partita occupa la giornata.",
    "Root": "Sotto l'aspetto di una favola animale c'è un conflitto profondamente asimmetrico: gatti industriali, uccelli in guerra, ribelli della foresta e un vagabondo giocano con regole e obiettivi completamente diversi.",
    "Crescent Moon": "Medio Oriente del X secolo: cinque fazioni molto diverse — sultano, califfo, nomadi, signore della guerra, cospiratore — si contendono il territorio fra alleanze temporanee, favori comprati e tradimenti.",
    "Zombicide: Dark Side": "Cooperativo a miniature in chiave post-apocalittica: si guida una squadra di sopravvissuti in scenari infestati, si recupera equipaggiamento e si abbattono orde che crescono man mano che si diventa più forti.",
    "Zombicide: Season 1": "Il capostipite della serie: sopravvissuti armati di quel che capita ripuliscono quartieri invasi dagli zombi. Più si sale di livello, più zombi compaiono — diventare potenti è anche il problema.",
    "In alto i calici": "A tavola con un veleno in mano: si passano e si scambiano carte per avvelenare il proprio bersaglio, bere più vino degli altri e soprattutto arrivare vivi al brindisi finale.",
    "When I Dream": "Un giocatore bendato è il sognatore; gli altri gli danno indizi di una parola sola, ma alcuni mentono di proposito. Alla fine il sognatore racconta ad alta voce il sogno che ha ricostruito.",
    "Pozioni esplosive": "Si sfilano le biglie da un distributore verticale: ogni presa fa franare le altre e può innescare reazioni a catena. Con gli ingredienti raccolti si completano le pozioni richieste.",
    "Camel Up": "Cammelli che si accavallano in groppa l'uno all'altro e scommesse da piazzare al momento giusto: si punta sulla tappa, sul vincitore finale e persino su chi arriverà ultimo.",
    "Sagrada": "Si costruisce una vetrata incastonando dadi colorati in una griglia che impone vincoli di colore e di valore. Un puzzle silenzioso, giocato con quello che gli altri hanno lasciato.",
    "Whitechapel": "Un giocatore è Jack lo Squartatore e si muove di nascosto annotando il percorso; gli altri sono i poliziotti che battono i vicoli di Londra per stringere il cerchio prima dell'alba.",
    "Splendor": "Mercanti del Rinascimento: si raccolgono gemme per comprare carte che a loro volta scontano gli acquisti successivi. Un motore che si accelera da solo, nel giro di mezz'ora.",
    "Cryptid": "Ognuno conosce un solo indizio sulla posizione della creatura. A turno si fanno domande e si escludono caselle, finché qualcuno incrocia abbastanza informazioni da trovarla.",
    "7 Wonders": "Tre ere di civiltà giocate a mano passante: si sceglie una carta e si cede il resto al vicino, costruendo intanto risorse, esercito, scienza e la propria meraviglia.",
    "Capitan Sonar": "Due sottomarini, due squadre, tutto in tempo reale: capitano, ufficiale, radarista e ingegnere devono coordinarsi a voce, nel caos, per localizzare e affondare l'avversario.",
    "Rock'n'Roll Robot": "Un rompicapo collettivo: tutti guardano la stessa griglia e cercano in quante mosse portare un robot all'obiettivo, sapendo che i robot scivolano finché non urtano qualcosa.",
    "Wings of War": "Duelli aerei della Grande Guerra: si programmano in segreto le manovre con le carte, si rivelano simultaneamente e si spara a chi finisce nel proprio cono di tiro.",
    "Zombicide: Marvel Zombies - X-Men Resistance": "Qui gli infetti sono i supereroi Marvel: si gioca dalla parte degli zombi o contro di loro, in scenari pieni di poteri speciali e di orde che non smettono mai di arrivare.",
    "Slay the Spire: il gioco da tavolo": "L'adattamento del videogioco: si sale una torre a piani costruendo il proprio mazzo di carte, gestendo energia e reliquie, verso boss sempre più duri. Si gioca anche da soli.",
    "Memoir '44": "Seconda guerra mondiale in miniatura: le carte comando dicono su quale settore del fronte si può agire e i dadi risolvono gli scontri. Ogni scenario ricostruisce una battaglia realmente avvenuta.",
    "Terra Nova": "Versione snella di Terra Mystica: ogni popolo trasforma il terreno nel proprio e si espande, cercando di restare vicino agli altri per guadagnare di più senza rimanere senza spazio.",
    "Trivial Pursuit": "Il quiz per eccellenza: si gira per il tabellone rispondendo a domande di sei categorie e raccogliendo gli spicchi colorati, fino alla domanda decisiva al centro.",
    "Avalon": "I fedeli di Artù devono portare a termine le missioni, gli scagnozzi di Mordred sabotarle. Merlino sa chi sono i cattivi, ma se si fa scoprire fa perdere la sua squadra.",
    "Legami di sangue": "Due clan di vampiri mescolati nella stessa stanza: si attacca, si deduce e si sospetta, finché uno dei due non riesce a identificare e catturare il capo avversario.",
    "Landmarks": "Nella giungla si indica un percorso ai compagni usando una parola per volta: chi ascolta deve collegare gli indizi e ricostruire la strada giusta verso il tesoro.",
    "Carcassonne": "Si pesca una tessera e la si incastra nel paesaggio, poi si decide se piazzarci sopra un omino per rivendicare una strada, una città o un monastero. I confini contano più del resto.",
    "Othello": "Un minuto per impararlo, una vita per padroneggiarlo: si racchiudono le pedine avversarie fra due proprie per capovolgerle. Vince chi alla fine ne ha di più del suo colore.",
    "Il gioco delle uova": "Si vincono uova con piccole prove di destrezza e poi bisogna tenerle addosso — sotto il mento, fra le ginocchia, nell'incavo del braccio — mentre la partita continua.",
    "Fuggi Fuggi!": "Si guida un gruppetto di personaggi fuori da un sotterraneo mentre un mostro li insegue; massi da spingere, pozze scivolose e teletrasporti complicano ogni fuga.",
    "Cash'n Guns": "Tutti puntano una pistola di gommapiuma contro qualcuno e devono decidere in un istante se restare o tirarsi indietro. Chi resta in piedi si spartisce il bottino.",
    "Ticket to Ride": "Si collezionano carte colorate per rivendicare tratte ferroviarie e collegare le città indicate dai propri biglietti, sperando che nessuno occupi prima il passaggio chiave.",
    "Similo": "Un giocatore dà indizi mostrando altre carte e dicendo soltanto se somigliano o no al personaggio segreto; insieme si scartano le carte fino a isolare quella giusta.",
    "Similo 2": "Stessa meccanica di Similo su un nuovo mazzo: indizi per somiglianza e per differenza, dodici carte sul tavolo e un numero limitato di tentativi per arrivare a quella giusta.",
    "Il grande Dalmuti": "Gerarchia spietata: si scartano gruppi di carte uguali per liberarsi la mano e a fine round si cambia posto al tavolo. Il primo comanda, l'ultimo mescola e serve da bere.",
    "Tsuro": "Si posano tessere con percorsi intrecciati e si segue la propria linea: chi finisce fuori dal tabellone o si scontra con un altro è eliminato. Vince l'ultimo rimasto in pista.",
    "Burrito": "Si scambiano carte alla ricerca di tris e, quando salta fuori la carta duello, si afferra il burrito di gommapiuma e lo si tira addosso all'avversario. Caos garantito.",
    "Oh Issa!": "Tiro alla fune in due: a ogni mano si divide il mazzetto e se ne passa metà all'avversario, poi si giocano le carte forza per aggiudicarsi i barili in palio.",
    "Kahuna": "Duello sulle isole del Pacifico: si giocano carte per costruire ponti e, quando si conquista la maggioranza dei collegamenti di un'isola, quelli dell'altro vengono spazzati via.",
    "King Up!": "Si muovono nobili condivisi verso il trono scommettendo di nascosto su chi arriverà in alto: conviene spingere anche i candidati degli altri per non farsi scoprire.",
    "Kamisado": "Astratto per due senza alcuna casualità: il colore della casella su cui arrivi decide con quale pezzo l'avversario dovrà muovere. Vince chi raggiunge per primo il lato opposto.",
    "Kingdomino": "Si scelgono tessere a due caselle in ordine di forza e le si incastra nel proprio regno cinque per cinque, accostando terreni uguali e concentrandoci sopra le corone.",
    "7 Wonders Duel": "7 Wonders rifatto per due: le carte sono disposte a piramide e si possono prendere solo quelle libere. Si vince ai punti, ma anche con l'esercito o con la scienza.",
    "Vudu": "Stregoni che si lanciano maledizioni buffe: parlare a bassa voce, tenere un braccio alzato, non piegare i gomiti. Si accumulano punti finché si riesce a rispettarle tutte.",
    "Topiary": "Si dispongono i visitatori lungo il bordo del giardino e si sistemano le siepi scolpite in modo che, dal proprio punto di vista, la fila davanti sia la più alta e varia possibile.",
    "Faraway": "Si gioca una carta per notte e alla fine si leggono i propri obiettivi al contrario: conta ciò che si è messo prima, quindi bisogna ragionare sulla partita a ritroso.",
    "Just One": "Una parola da indovinare, tutti scrivono un indizio di una parola sola — e gli indizi identici si cancellano a vicenda. Cooperativo: si vince o si perde insieme.",
    "Cartagena": "Evasione dal forte: si scartano carte per far avanzare i pirati verso la barca, ma per recuperarne bisogna tornare indietro. O si esce tutti, o non è uscito nessuno.",
    "3 Segreti": "Quindici minuti per risolvere un caso: si fanno domande a chi conosce la verità, che può rispondere solo sì o no, fino a ricostruire i tre segreti nascosti.",
    "Fort": "Si mette insieme una banda di bambini giocando carte, ma quelle che non si usano possono essere prese dagli altri: il mazzo va sfruttato tutto, e va sfruttato in fretta.",
    "Nome in codice": "Due squadre, una griglia di parole e un capitano che può dire una sola parola e un numero per far indovinare più agenti possibile — evitando a ogni costo l'assassino.",
    "Not Alone": "Un giocatore è la Creatura che dà la caccia, gli altri sono i naufraghi che si nascondono giocando in segreto i luoghi dell'isola, sperando di non incrociarla.",
    "Guillotine": "Rivoluzione francese in chiave comica: si riordina la fila dei nobili in attesa del patibolo per accaparrarsi, al proprio turno, le teste che valgono di più.",
    "Bang!": "Far West a ruoli nascosti: lo sceriffo è allo scoperto, fuorilegge, vice e rinnegato no. Si spara a distanza di carte cercando di capire chi vuole davvero la tua pelle.",
    "Imagine": "Si compone un'immagine sovrapponendo e muovendo carte trasparenti per far indovinare un film, un personaggio, un modo di dire. Niente parole, solo forme.",
    "Decripto": "La propria squadra deve capire il codice dai tuoi indizi, l'altra ascolta e prova a intercettarlo. Più indizi dai nel corso della partita, più rischi di farti decifrare.",
    "Unstable Unicorns": "Si mette insieme una stalla di unicorni mentre gli altri provano a smantellarla con carte magiche e sabotaggi. Cattiveria pura, in versione pastello.",
    "Tags": "Nomi, cose e città rivisitato: da una griglia di lettere e categorie si tirano fuori parole valide più in fretta degli altri, da soli o divisi in squadre.",
    "Colt Express": "Si programmano in anticipo le mosse dei banditi su un treno tridimensionale, poi si esegue tutto nell'ordine stabilito — e quasi mai come lo si era immaginato.",
    "Mysterium": "Un fantasma comunica solo con grandi carte illustrate oniriche; i medium devono interpretarle per ricostruire assassino, arma e luogo prima che scadano le notti.",
    "Sator Arepo Tenet Opera Rotas": "Sopra un abisso, monaci camminano su passerelle mobili: si giocano carte per ruotare i ponti e raggiungere i propri quattro libri prima degli avversari.",
    "MicroMacro": "Una mappa enorme piena di scenette: le carte pongono domande su un delitto e la risposta va cercata fra le figure, seguendo i personaggi da un angolo all'altro della città.",
    "La casa delle mannaie": "Chiusi in una villa maledetta, si passa di stanza in stanza per raccogliere monete e, all'occorrenza, per togliere di mezzo qualcun altro. Solo carte, molto rumore.",
    "Dungeon WC": "Cinque minuti di panico cooperativo in tempo reale: bisogna portare l'eroe al bagno prima che scada la clessidra, superando i mostri che si mettono in mezzo.",
    "Rock Paper Wizard": "I maghi si contendono il tesoro lanciandosi incantesimi decisi con le dita, alla morra cinese: si conta fino a tre e si scopre chi ha colpito chi.",
    "Rush & Bash": "Corse demenziali su circuiti con vulcani e ponti sospesi: ogni carta dà insieme un movimento e un effetto — missili, mine, riparazioni — da usare al momento giusto.",
    "Otto minuti per un impero": "Un gioco di conquista ridotto all'osso: poche azioni a testa, una manciata di minuti e la mappa è già decisa fra truppe piazzate e carte merce raccolte.",
    "Sky Team": "In due nella cabina di un aereo: uno è il pilota, l'altro il copilota. Si piazzano i dadi sui comandi senza poter parlare, cercando di atterrare senza disastri.",
    "Tristerra: La Grande Baldoria": "Un mazzo solo, due modi di usarlo: come party game fantasy fra amici oppure come piccola avventura di ruolo, con la stessa ambientazione e gli stessi personaggi.",
    "Room 25": "Rinchiusi in un complesso di stanze mortali, si programmano le mosse per trovare l'uscita — sapendo che qualcuno del gruppo potrebbe lavorare per i carcerieri.",
    "Nome in codice: Visual": "Come Nome in codice, ma la griglia è fatta di illustrazioni piene di dettagli: l'indizio deve agganciare quello che si vede, non quello che si legge.",
    "The Resistance": "Una cellula di ribelli e qualche spia infiltrata: si vota chi mandare in missione e si osserva chi la fa fallire, discutendo e sospettando a ogni round.",
    "Lupusburg": "Lupus in tabula concentrato per gruppi piccoli: di notte il lupo mannaro colpisce, di giorno il villaggio lincia un sospetto, e i ruoli speciali cambiano a ogni partita.",
    "Happy Little Dinosaurs": "Dinosauri che cercano di sopravvivere a meteore e disgrazie assortite: si schivano i disastri con le carte in mano e si spera che tocchi a qualcun altro.",
    "Marvel Villainous": "Ogni cattivo ha obiettivo e mazzo suoi: si persegue il proprio piano mentre gli altri ti mettono i bastoni fra le ruote giocando carte destino contro di te.",
    "Pastiche": "Si mescolano colori primari come su una tavolozza per riprodurre la gamma di quadri famosi e incassare le commissioni. Elegante, e si impara qualcosa di storia dell'arte.",
    "Uno": "Si scartano carte per colore o numero, si affibbiano pescate agli avversari e si grida «Uno» quando ne resta una sola in mano — o si paga il silenzio.",
    "Sei": "Quattro file sul tavolo e carte numerate da piazzare: chi appoggia la sesta carta di una fila si porta via tutte le precedenti con i loro punti di penalità.",
    "Stay Away!": "Un'entità aliena infetta il gruppo e si diffonde passando carte di mano in mano: bisogna capire chi è ancora umano prima che il contagio prenda il sopravvento.",
    "Tesseract": "Un blocco di sessantaquattro dadi da smontare con metodo: la squadra li estrae, ne modifica i valori e li isola nella matrice di contenimento senza far crollare tutto.",
    "Mascarade": "Tutti conoscono il proprio ruolo, poi le carte vengono scambiate sotto il tavolo e nessuno è più sicuro di niente. Si dichiara un personaggio e si aspetta chi smentisce.",
    "Intrighi a corte": "Tre carte per turno: una davanti a sé, una davanti a un avversario e una sul tavolo della regina. Bisogna far salire le famiglie giuste e affondare quelle degli altri.",
    "Timeline": "Si inserisce una carta nella linea del tempo indovinando se l'invenzione o l'evento venga prima o dopo quelli già disposti. Vince chi si libera per primo delle sue carte.",
    "Gloom": "Si racconta la vita sempre più sfortunata della propria famiglia gotica: si accumulano disgrazie sui propri personaggi e poi li si manda incontro a una fine adeguatamente tragica.",
    "RRR": "Astratto secco per due: nove regni disposti in griglia e sette carte a testa da giocare per rivendicarli. Quando la griglia è piena vince chi ne controlla di più.",
    "Mangia Preda Chiama": "Cinque animali in ordine di forza e tutti giocano una carta coperta. Quando il proprio animale viene chiamato bisogna svelarsi e provare a mangiare chi sta più in basso.",
    "Korsar": "Galeoni carichi d'oro e pirati di quattro colori: si accumulano forze su una nave e si incassa il bottino quando, al proprio turno, si ha la maggioranza.",
    "Warehouse 51": "Si battono all'asta reliquie leggendarie — l'Arca, la lampada di Aladino — sapendo che alcune sono falsi e che dei falsi ogni giocatore conosce solo una parte.",
    "Munchkin Cthulhu": "Si scende nel dungeon per salire di livello, ma soprattutto per sabotare gli altri sul più bello. Parodia, carte cattive e nessuna pietà per chi sta per vincere.",
    "Zombie Dice": "Si pescano dadi dal barattolo e si tira: cervelli da incassare, colpi di fucile che fermano tutto. Si continua finché si ha il coraggio di continuare.",
    "One Zero One": "Duello astratto fra zeri e uni: si posano carte nelle righe di codice e si usano i comandi per ribaltare la situazione prima che il programma venga eseguito.",
    "Venice Connection": "Cinque minuti di puro astratto: si accostano tessere di canale cercando di chiudere un circuito e allo stesso tempo di impedire all'avversario di farlo.",
    "7 - The Sins": "Si raccolgono carte dei sette peccati ricordando quelle già passate: eccedere in un vizio condanna all'abisso, restare troppo virtuosi non paga. Conta la misura.",
    "Kluster": "Sassi magnetici da posare uno alla volta dentro un cordoncino: se si attirano fra loro, chi li ha fatti scattare se li riprende in mano. Vince chi li piazza tutti.",
    "Niet!": "Prima di giocare le carte si decide insieme, eliminando un'opzione per volta, quali saranno le regole della mano: atout, valore delle prese, chi comincia, quanto si scarta.",
    "Orifiamma": "Si dispone una fila di personaggi coperti: ognuno può essere rivelato per usarne il potere oppure lasciato nascosto per incassare influenza, indovinando le mosse degli altri.",
    "Skull": "Si punta fiore o teschio a faccia in giù, poi si scommette su quante carte si riesce a scoprire senza trovare un teschio. Nessun tabellone: solo bluff e facce.",
    "Cortex": "Una serie di prove lampo — memoria, percorsi, tatto, logica, calcolo — in cui conta solo arrivare per primi con la risposta giusta, prima ancora di aver capito la domanda.",
    "Match Up! Cose": "Si dispongono le carte parola sul tavolo e si associano agli indizi letti a voce alta, tutti insieme, scegliendo quanto rendersi la vita difficile.",
    "Match Up! Cibo": "Stessa formula di Match Up! con un mazzo dedicato alla cucina: indizi da leggere ad alta voce e parole da abbinare, in cooperativa e a difficoltà regolabile.",
    "7 Rosso": "Ogni carta giocata cambia la regola che stabilisce chi sta vincendo: al termine del proprio turno bisogna trovarsi in testa secondo la regola del momento, o si è fuori.",
    "The Game": "Quattro pile, due che salgono e due che scendono: si scartano carte quasi in silenzio, potendo scambiare pochissime informazioni, provando a svuotare il mazzo.",
    "I Cattivissimi 7": "Si conta da uno a sette e ritorno scoprendo carte, ma i personaggi raffigurati cambiano le regole al volo: chi sbaglia il conto si prende tutto il mazzetto.",
    "Coloretto": "Si aggiungono carte alle file oppure se ne prende una intera: alla fine solo tre colori danno punti e gli altri li tolgono. Decidere quando fermarsi è tutto il gioco.",
    "Deckscape: Il destino di Londra": "Escape room contenuta in un mazzo di carte: si legge, si discute e si decide insieme, e ogni errore costa tempo. Qui si indaga su un complotto fra le strade di Londra.",
    "Deckscape: Fuga da Alcatraz": "Escape room in un mazzo di carte, da giocare in gruppo senza preparazione: enigmi da risolvere insieme per evadere dal carcere più duro d'America.",
    "Deckscape: Ciurma contro ciurma": "Variante competitiva della serie: due ciurme giocano lo stesso mazzo fianco a fianco e vince chi risolve gli enigmi piratereschi commettendo meno errori.",
    "Deckscape: Il mistero di Eldorado": "Escape room in un mazzo di carte: si attraversa la giungla sulle tracce della città d'oro, risolvendo enigmi in gruppo e pagando ogni errore in tempo perso.",
    "Deckscape: L'ora del test": "Il primo della serie: chiusi in un laboratorio, si risolvono insieme gli enigmi di un test che si rivela più insidioso del previsto. Bastano il mazzo e un tavolo.",
    "Burst": "Si gioca una carta per volta su una fila comune: superare ventuno fa saltare il banco e chi ha causato il disastro resta a mani vuote mentre gli altri incassano.",
    "Blind Jack": "Quiz con risposte numeriche da zero a dieci: si stima il valore nascosto e si decide se tenere la carta o passare, cercando di avvicinarsi a ventuno senza sballare.",
    "Claim": "Prese in due divise in due tempi: nella prima metà si vincono le carte che formeranno il proprio esercito, nella seconda si combatte proprio con quello che si è raccolto.",
    "Muffin Time": "Carte assurde giocabili in qualsiasi momento, anche nel turno degli altri: si accumulano oggetti e si sabota chi sta per vincere, spesso all'ultimo secondo utile.",
    "Zombie Fluxx": "Le regole cambiano di continuo perché sono esse stesse carte da giocare: obiettivi e condizioni di vittoria si trasformano mentre gli zombi si accumulano sul tavolo.",
    "Paroliere": "Si agita la griglia di dadi con le lettere e in un minuto si scrivono più parole possibile collegando lettere adiacenti. Le parole trovate anche da altri non contano.",
    "Minotaurus": "Labirinto di mattoncini che cambia forma: si tira il dado per portare i propri eroi al tempio, spostando i muri e scatenando il minotauro sui personaggi degli altri.",
    "Giorno di paga": "Un mese di calendario da attraversare fra bollette, affari e imprevisti; a fine mese arriva lo stipendio e si saldano i debiti. Vince chi ha messo da parte di più.",
    "Domino": "Le tessere si accostano per numeri uguali, allungando una catena in entrambe le direzioni finché qualcuno non riesce più a muovere o esaurisce la mano.",
    "Radio Londra": "Uno speaker descrive due carte con una frase in codice: la propria squadra deve riconoscerle, l'altra ascolta e prova a intercettare il messaggio prima di loro.",
    "Villa Paletti": "Si sfilano colonne di legno dai piani già costruiti e le si rimette più in alto: la torre cresce, si assottiglia e traballa, finché qualcuno la fa crollare.",
    "Boon Lake": "Si colonizza una terra selvaggia costruendo case, allevando animali e innescando catene di azioni sempre più efficienti. Ci si sposta solo dove sono già passati gli altri.",
    "Flick 'em Up!": "Far West a schicchere: si spara ai barili e ai banditi con un colpo di dito, si cavalca, si rapina la banca. Tutto si risolve con la mira, non con i dadi.",
    "Turing Machine": "Una macchina logica verifica le ipotesi: si interrogano i criteri e si escludono combinazioni finché resta un solo codice possibile. Nessuna app, solo carte forate.",
    "Super Farmer": "Si tirano due dadi con gli animali e si vedono le greggi crescere, sperando che la volpe e il lupo passino dalla parte degli altri. Si scambia per salire di specie.",
    "Shit Happens": "Si ordinano le disgrazie della vita quotidiana secondo quanto sono terribili, discutendo animatamente su che cosa sia davvero peggio. Per adulti, senza filtri.",
    "What Do You Meme?": "Si abbina la didascalia più divertente a un'immagine e un giudice a rotazione decide quale vince. Il bello è la discussione che segue ogni verdetto.",
    "Bad People": "Domande scomode sul gruppo: si vota chi fra i presenti corrisponde meglio alla descrizione. Da giocare solo con chi sa prenderla bene.",
    "Hive": "Scacchi senza scacchiera: si posano tessere esagonali con insetti, ognuno con un movimento proprio, per accerchiare completamente l'ape regina avversaria.",
    "Dobble": "Fra due carte qualsiasi c'è sempre un solo simbolo in comune: vince chi lo vede e lo nomina per primo. Cinque modi di giocare, cinque minuti a partita.",
    "Bananagrams": "Ognuno costruisce il proprio cruciverba con le tessere lettera, senza turni e senza aspettare: quando qualcuno finisce i pezzi, tutti ne pescano un altro.",
    "Fantozzi - Batti lei": "Memory a tema Fantozzi: si accoppiano scene e battute dei primi due film, con l'effetto comico che fa buona parte del lavoro al posto delle regole.",
    "Master Bluff": "Si dichiara quello che si sta giocando, ma nessuno controlla finché qualcuno non chiama il bluff. Poche carte, venti minuti e parecchie bugie.",
    "Lupi Mannari": "Il classico da gruppo numeroso: di notte i lupi scelgono una vittima, di giorno il villaggio discute e vota chi eliminare. Serve qualcuno che faccia da narratore.",
    "Il trauma del tram": "Un tram fuori controllo e due binari: due squadre argomentano per convincere il macchinista a schiacciare gli altri. Il dilemma del carrello, in versione irriverente.",
    "Bag of Chips": "Si pescano patatine colorate dal sacchetto e si scommette su quali obiettivi si riuscirà a completare, scartando per tempo quelli ormai diventati impossibili.",
    "Uno Golf": "Uno incrociato con il gioco del golf: si dispongono sei carte coperte e si cerca di abbassare il proprio punteggio scambiandole, invece di liberarsi della mano.",
    "Dadi poker": "Cinque dadi con i semi delle carte: si tira fino a tre volte cercando la combinazione migliore — scala, full, poker — e si segna il punteggio sul foglio.",
    "Perudo": "Si dichiara quanti dadi di un certo valore ci sono sotto tutti i bicchieri del tavolo, rilanciando oppure smascherando chi ha esagerato. Il bluff dei pirati.",
    "Scacchi": "Il gioco di strategia per eccellenza: sedici pezzi per parte, nessun elemento casuale e un solo obiettivo, mettere sotto scacco matto il re avversario.",
}
